baseURL = 'https://cleanskinaesthetics.beauty/'
languageCode = 'en-us'
publishDir = 'docs'
theme = "clear-skin-theme"
title = 'Clear Skin Aesthetics'
removePathAccents = true
enableRobotsTXT = true

[build]
  buildDrafts = true
[[build.cachebusters]]
  source = '(postcss|tailwind)\.config\.js'
  target = 'css'

[markup]
  [markup.goldmark.renderer]
    unsafe = true

[minify]
  disableHTML = true

[outputFormats.PostCSS]
  baseName = "css/tailwind"
  mediaType = "text/css"
  isPlainText = true
  notAlternative = true
